resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:27a3d49362bda15c60d5a7f87a3fdbcd147604235bb95d549c3d9100a4155b81
  name: quay.io/abass0/quinoa-wind-turbine
