resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:3df7d90076a8320f27f3ddc9bd364a2781bec24f6e573b9066bc6301dacf7b24
  name: quay.io/rhdevelopers/quinoa-wind-turbine
