resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:fd6930ddaf318598ce9d0036314ee84684eb0e4ea95f09bfd25867db017521f9
  name: quay.io/abass0/quinoa-wind-turbine
