resources:
- deployment.yaml
- service.yaml
- route.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:1e8b731be964bd37898f136137436315aa5f917cc810714318eb19a7e0fa59d0
  name: quay.io/abass0/quinoa-wind-turbine
